/**
 * @description JavaScript tracker for Snowplow
 * @version     2.16.3
 * @copyright   Anthon Pang, Snowplow Analytics Ltd
 * @license     Simplified BSD
 * 
 * Documentation: http://bit.ly/sp-js
 */

'use strict';(function(Oc){function K(a){"@babel/helpers - typeof";K="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return K(a)}function ja(a,b,c){return c={path:b,exports:{},require:function(a,b){throw Error("Dynamic requires are not currently supported by @rollup/plugin-commonjs");}},a(c,c.exports),c.exports}function ka(a){var b=-1,c=null==
a?0:a.length;for(this.clear();++b<c;){var d=a[b];this.set(d[0],d[1])}}function V(a){var b=-1,c=null==a?0:a.length;for(this.clear();++b<c;){var d=a[b];this.set(d[0],d[1])}}function la(a){var b=-1,c=null==a?0:a.length;for(this.clear();++b<c;){var d=a[b];this.set(d[0],d[1])}}function ma(a){this.size=(this.__data__=new wa(a)).size}function Na(a){var b=-1,c=null==a?0:a.length;for(this.__data__=new na;++b<c;)this.add(a[b])}function oa(a,b,c,d,e){if(a===b)b=!0;else if(null==a||null==b||!W(a)&&!W(b))b=a!==
a&&b!==b;else a:{var f=A(a),g=A(b),h=f?"[object Array]":eb(a),l=g?"[object Array]":eb(b);h="[object Arguments]"==h?"[object Object]":h;l="[object Arguments]"==l?"[object Object]":l;var m="[object Object]"==h;g="[object Object]"==l;if((l=h==l)&&fb(a)){if(!fb(b)){b=!1;break a}f=!0;m=!1}if(l&&!m)e||(e=new xa),b=f||xb(a)?gb(a,b,c,d,oa,e):Pc(a,b,h,c,d,oa,e);else{if(!(c&1)&&(f=m&&yb.call(a,"__wrapped__"),h=g&&yb.call(b,"__wrapped__"),f||h)){a=f?a.value():a;b=h?b.value():b;e||(e=new xa);b=oa(a,b,c,d,e);
break a}if(l)b:if(e||(e=new xa),f=c&1,h=hb(a,ya,ib),g=h.length,l=hb(b,ya,ib).length,g==l||f){for(l=g;l--;){var r=h[l];if(!(f?r in b:Qc.call(b,r))){b=!1;break b}}m=e.get(a);r=e.get(b);if(m&&r)b=m==b&&r==a;else{m=!0;e.set(a,b);e.set(b,a);for(var p=f;++l<g;){r=h[l];var zb=a[r],Ab=b[r];if(d)var L=f?d(Ab,zb,r,b,a,e):d(zb,Ab,r,a,b,e);if(void 0===L?zb!==Ab&&!oa(zb,Ab,c,d,e):!L){m=!1;break}p||(p="constructor"==r)}m&&!p&&(c=a.constructor,d=b.constructor,c!=d&&"constructor"in a&&"constructor"in b&&!("function"==
typeof c&&c instanceof c&&"function"==typeof d&&d instanceof d)&&(m=!1));e["delete"](a);e["delete"](b);b=m}}else b=!1;else b=!1}}return b}function jb(a,b){if("function"!=typeof a||null!=b&&"function"!=typeof b)throw new TypeError("Expected a function");var c=function e(){var c=arguments,g=b?b.apply(this,c):c[0],h=e.cache;if(h.has(g))return h.get(g);c=a.apply(this,c);e.cache=h.set(g,c)||h;return c};c.cache=new (jb.Cache||na);return c}function kb(a){if("string"==typeof a)return a;if(A(a))return lb(a,
kb)+"";if(pa(a))return mb?mb.call(a):"";var b=a+"";return"0"==b&&1/a==-Rc?"-0":b}function ec(a){if(!Bb(a)){a=a.text||"";var b=za.getElementsByTagName("title");b&&void 0!==b[0]&&(a=b[0].text)}return a}function Cb(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return b?b[1]:a}function Nb(a){var b=a.length;"."===a.charAt(--b)&&(a=a.slice(0,b));"*."===a.slice(0,2)&&(a=a.slice(1));return a}function Ob(a){var b="",c=nb("referrer",aa.location.href)||nb("referer",aa.location.href);if(c)return c;
if(a)return a;try{b=aa.top.document.referrer}catch(d){if(aa.parent)try{b=aa.parent.document.referrer}catch(e){b=""}}""===b&&(b=za.referrer);return b}function B(a,b,c,d){if(a.addEventListener)return a.addEventListener(b,c,d),!0;if(a.attachEvent)return a.attachEvent("on"+b,c);a["on"+b]=c}function nb(a,b){return(a=(new RegExp("^[^#]*[?&]"+a+"=([^&#]*)")).exec(b))?decodeURIComponent(a[1].replace(/\+/g," ")):null}function Oa(a){var b=Array.prototype.slice.call(arguments,1);return Sc(Aa(a,function(a){if("function"===
typeof a)try{return a.apply(null,b)}catch(d){}else return a}))}function y(a){"undefined"!==typeof console&&console.warn("Snowplow: "+a)}function Pa(a){return a.className.match(/\S+/g)||[]}function Qa(a,b){if(Array.isArray(a)||!N(a))return function(){return!0};if(a.hasOwnProperty("filter"))return a.filter;var c=a.hasOwnProperty("whitelist");a=a.whitelist||a.blacklist;Array.isArray(a)||(a=[a]);for(var d={},e=0;e<a.length;e++)d[a[e]]=!0;return b?function(a){a:{a=Pa(a);var b;for(b=0;b<a.length;b++)if(d[a[b]]){a=
!0;break a}a=!1}return a===c}:function(a){return a.name in d===c}}function Tc(a){return N(a)?a.hasOwnProperty("transform")?a.transform:function(a){return a}:function(a){return a}}function Db(a,b){var c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:63072E3;try{var d=Date.now()+1E3*c;R.setItem("".concat(a,".expires"),d);R.setItem(a,b);return!0}catch(e){return!1}}function fc(a){try{return R.removeItem(a),R.removeItem(a+".expires"),!0}catch(b){return!1}}function Uc(){for(var a="_sp_root_domain_test_"+
(new Date).getTime(),b="_test_value_"+(new Date).getTime(),c=aa.location.hostname.split("."),d=c.length-1;0<=d;){var e=c.slice(d,c.length).join(".");D(a,b,0,"/",e);if(D(a)===b){D(a,"",-1,"/",e);a=za.cookie.split("; ");b=[];for(c=0;c<a.length;c++)"_sp_root_domain_test_"===a[c].substring(0,21)&&b.push(a[c]);a=b;for(b=0;b<a.length;b++)D(a[b],"",-1,"/",e);return e}--d}return aa.location.hostname}function gc(a,b){for(var c=0;c<b.length;c++)if(b[c]===a)return!0;return!1}function D(a,b,c,d,e,f,g){return 1<
arguments.length?za.cookie=a+"="+encodeURIComponent(b)+(c?"; Expires="+(new Date(+new Date+1E3*c)).toUTCString():"")+(d?"; Path="+d:"")+(e?"; Domain="+e:"")+(f?"; SameSite="+f:"")+(g?"; Secure":""):decodeURIComponent((("; "+za.cookie).split("; "+a+"=")[1]||"").split(";")[0])}function Ra(a){a=parseInt(a);return isNaN(a)?void 0:a}function ob(a){a=parseFloat(a);return isNaN(a)?void 0:a}function Ba(a){return a&&"function"===typeof a?!0:!1}function Vc(a,b,c,d,e){function f(d,f,g){g=g||{};h.hasOwnProperty(d)?
y("Tracker namespace "+d+" already exists."):(h[d]=new a(e,d,b,c,g),h[d].setCollectorUrl(f))}function g(){var a;for(a=0;a<arguments.length;a+=1){var b=arguments[a];var c=Array.prototype.shift.call(b);if(Ba(c))try{c.apply(h,b)}catch(Wc){y("Custom callback error - ".concat(Wc))}finally{continue}var d=c.split(":");c=d[0];d=1<d.length?d[1].split(";"):[];d=[c,d];c=d[0];d=d[1];if("newTracker"===c)f(b[0],b[1],b[2]);else if("setCollectorCf"!==c&&"setCollectorUrl"!==c||d&&0!==d.length){var e=[];if(d&&0!==
d.length)for(var g=0;g<d.length;g++)h.hasOwnProperty(d[g])?e.push(h[d[g]]):y('Warning: Tracker namespace "'+d[g]+'" not configured');else e=Aa(h);0===e.length&&y("Warning: No tracker configured");for(d=0;d<e.length;d++)e[d][c].apply(e[d],b)}else d=b[0],b=b[1],y(c+" is deprecated. Set the collector when a new tracker instance using newTracker."),b=void 0===b?"sp":b,f(b),h[b][c](d)}}for(var h={},l=0;l<d.length;l++)g(d[l]);return{push:g}}function hc(a,b,c){if("translate.googleusercontent.com"===a)""===
c&&(c=b),a=/^(?:https?|ftp)(?::\/*(?:[^?]+))([?][^#]+)/.exec(b),b=nb("u",a[1]),a=Cb(b);else{var d;if(!(d="cc.bingj.com"===a||"webcache.googleusercontent.com"===a))a:{if(/^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test(a))try{var e=document.body.children[0].children[0].children[0].children[0].children[0].children[0].innerHTML;d="You have reached the cached page for"===e.slice(0,36);
break a}catch(f){d=!1;break a}d=void 0}d&&(b=document.links[0].href,a=Cb(b))}return[a,b,c]}function Xc(){try{var a=!!qa.localStorage}catch(b){a=!0}if(!a)return!1;try{return qa.localStorage.setItem("modernizr","modernizr"),qa.localStorage.removeItem("modernizr"),!0}catch(b){return!1}}function Yc(){var a=qa,b="inner";"innerWidth"in qa||(b="client",a=ra.documentElement||ra.body);var c=a[b+"Width"];a=a[b+"Height"];return 0<=c&&0<=a?c+"x"+a:null}function Zc(){var a=ra.documentElement,b=ra.body,c=Math.max(a.clientWidth,
a.offsetWidth,a.scrollWidth);a=Math.max(a.clientHeight,a.offsetHeight,a.scrollHeight,b?Math.max(b.offsetHeight,b.scrollHeight):0);return isNaN(c)||isNaN(a)?"":c+"x"+a}function $c(a,b){var c,d={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},e={};if(H.mimeTypes&&H.mimeTypes.length)for(c in d)if(Object.prototype.hasOwnProperty.call(d,
c)){var f=H.mimeTypes[d[c]];e[c]=f&&f.enabledPlugin?"1":"0"}H.constructor===window.Navigator&&"unknown"!==typeof H.javaEnabled&&void 0!==H.javaEnabled&&H.javaEnabled()&&(e.java="1");Ba(qa.GearsFactory)&&(e.gears="1");e.res=Sa.width+"x"+Sa.height;e.cd=Sa.colorDepth;a&&(a=b||"testcookie",void 0===H.cookieEnabled?(D(a,"1"),a="1"===D(a)?"1":"0"):a=H.cookieEnabled?"1":"0",e.cookie=a);return e}function ad(a,b,c){function d(b,d){for(var e,f,g,l;null!==(e=b.parentNode)&&void 0!==e&&"A"!==(f=b.tagName.toUpperCase())&&
"AREA"!==f;)b=e;if(void 0!==b.href){e=b.hostname||Cb(b.href);f=e.toLowerCase();var m=b.href.replace(e,f);/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(m)||(e=b.id,f=Pa(b),g=b.target,l=h?b.innerHTML:null,m=unescape(m),a.trackLinkClick(m,e,f,g,l,c(Oa(d,b))))}}function e(a){return function(b){b=b||window.event;var c=b.which||b.button;var e=b.target||b.srcElement;"click"===b.type?e&&d(e,a):"mousedown"===b.type?1!==c&&2!==c||!e?m=r=null:(m=c,r=e):"mouseup"===b.type&&(c===m&&
e===r&&d(e,a),m=r=null)}}var f,g,h,l,m,r;return{configureLinkClickTracking:function(a,b,c,d){h=c;l=d;g=b;f=Qa(a,!0)},addClickListeners:function(){var a=document.links,c;for(c=0;c<a.length;c++)if(f(a[c])&&!a[c][b]){var d=a[c];g?(B(d,"mouseup",e(l),!1),B(d,"mousedown",e(l),!1)):B(d,"click",e(l),!1);a[c][b]=!0}}}}function bd(a,b,c){function d(a){return a[cd(["name","id","type","nodeName"],function(b){return a[b]&&"string"===typeof a[b]})]}function e(a){for(;a&&a.nodeName&&"HTML"!==a.nodeName.toUpperCase()&&
"FORM"!==a.nodeName.toUpperCase();)a=a.parentNode;if(a&&a.nodeName&&"FORM"===a.nodeName.toUpperCase())return d(a)}function f(a){var b=[];z(l,function(c){c=Array.prototype.filter.call(a.getElementsByTagName(c),function(a){return a.hasOwnProperty(m)});z(c,function(a){if("submit"!==a.type){var c={name:d(a),value:a.value,nodeName:a.nodeName,id:a.id};a.type&&"INPUT"===a.nodeName.toUpperCase()&&(c.type=a.type);"checkbox"!==a.type&&"radio"!==a.type||a.checked||(c.value=null);b.push(c)}})});return b}function g(b,
f){return function(g){g=g.target;var h=g.nodeName&&"INPUT"===g.nodeName.toUpperCase()?g.type:null,l="checkbox"!==g.type||g.checked?n(g.value,g):null;("change_form"===b||"checkbox"!==h&&"radio"!==h)&&a.trackFormFocusOrChange(b,e(g),d(g),g.nodeName,h,Pa(g),l,c(Oa(f,g,h,l)))}}function h(b){return function(e){e=e.target;var g=f(e);z(g,function(a){a.value=n(a.value,a)});a.trackFormSubmission(d(e),Pa(e),g,c(Oa(b,e,g)))}}var l=["textarea","input","select"],m=b+"form",r=function(){return!0},p=function(){return!0},
n=function(a){return a};return{configureFormTracking:function(a){a&&(r=Qa(a.forms,!0),p=Qa(a.fields,!1),n=Tc(a.fields))},addFormListeners:function(a){z(document.getElementsByTagName("form"),function(b){r(b)&&!b[m]&&(z(l,function(c){z(b.getElementsByTagName(c),function(b){p(b)&&!b[m]&&"password"!==b.type.toLowerCase()&&(B(b,"focus",g("focus_form",a),!1),B(b,"change",g("change_form",a),!1),b[m]=!0)})}),B(b,"submit",h(a)),b[m]=!0)})}}}function dd(a){function b(b,d,e,f,g,h){a.trackSelfDescribingEvent({schema:"iglu:com.snowplowanalytics.snowplow/application_error/jsonschema/1-0-1",
data:{programmingLanguage:"JAVASCRIPT",message:b||"JS Exception. Browser doesn't support ErrorEvent API",stackTrace:g&&g.stack?g.stack:null,lineNumber:e,lineColumn:f,fileName:d}},h)}return{trackError:b,enableErrorTracking:function(a,d,e){B(ed,"error",function(c){if(Ba(a)&&a(c)||null==a){var g=Ba(d)?e.concat(d(c)):e;b(c.message,c.filename,c.lineno,c.colno,c.error,g)}},!0)}}}function ic(a,b,c,d,e,f,g,h,l,m,r){function p(a){var b="?",c={co:!0,cx:!0},d=!0,e;for(e in a)a.hasOwnProperty(e)&&!c.hasOwnProperty(e)&&
(d?d=!1:b+="&",b+=encodeURIComponent(e)+"="+encodeURIComponent(a[e]));for(var g in c)a.hasOwnProperty(g)&&c.hasOwnProperty(g)&&(b+="&"+g+"="+encodeURIComponent(a[g]));return b}function n(a){a=fd(a,function(a){return a.toString()});return{evt:a,bytes:t(JSON.stringify(a))}}function t(a){for(var b=0,c=0;c<a.length;c++){var d=a.charCodeAt(c);127>=d?b+=1:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,c++):b=65535>d?b+3:b+4}return b}function L(){for(;x.length&&"string"!==typeof x[0]&&"object"!==K(x[0]);)x.shift();
if(1>x.length)F=!1;else{if(!Bb(z))throw"No Snowplow collector configured, cannot track";F=!0;var a=x[0];if(O){var b=function(a){for(var b=0;b<a;b++)x.shift();d&&Db(u,JSON.stringify(x.slice(0,m)));L()},c=B(z),e=setTimeout(function(){c.abort();F=!1},r),g=function(a){for(var b=0,c=0;b<a.length&&!(c+=a[b].bytes,c>=h);)b+=1;return b}(x);c.onreadystatechange=function(){if(4===c.readyState&&200<=c.status&&400>c.status){clearTimeout(e);if(J&&!H)try{kc.setItem(R,!0)}catch(jc){}b(g)}else 4===c.readyState&&
400<=c.status&&(clearTimeout(e),F=!1)};a=Aa(x.slice(0,g),function(a){return a.evt});if(0<a.length){var f;if(!(f=H)&&(f=J))try{f=kc.getItem(R)}catch(jc){f=void 0}if(H=f){f=new Blob([D(A(a))],{type:"application/json"});try{var p=navigator.sendBeacon(z,f)}catch(jc){p=!1}}!0===p&&b(g);J&&p||c.send(D(A(a)))}}else{p=new Image(1,1);var n=!0;p.onload=function(){n&&(n=!1,x.shift(),d&&Db(u,JSON.stringify(x.slice(0,m))),L())};p.onerror=function(){n&&(F=n=!1)};p.src=l?z+a.replace("?","?stm="+(new Date).getTime()+
"&"):z+a;setTimeout(function(){n&&F&&(n=!1,L())},r)}}}function B(a){var b=new XMLHttpRequest;b.open("POST",a,!0);b.withCredentials=!0;b.setRequestHeader("Content-Type","application/json; charset=UTF-8");return b}function D(a){return JSON.stringify({schema:"iglu:com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-4",data:a})}function A(a){for(var b=(new Date).getTime().toString(),c=0;c<a.length;c++)a[c].stm=b;return a}var C=window.localStorage,F=!1,z,H;e=e.toLowerCase?e.toLowerCase():e;var Q=
null===e||!0===e||"beacon"===e||"true"===e,J=!!(Q&&navigator&&navigator.sendBeacon)&&Q,O=("post"===e||J)&&"get"!==e,N=(O=O&&!!(window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest))?f:"/i";g=Xc()&&d&&O&&g||1;var u="snowplowOutQueue_".concat(a,"_").concat(b,"_").concat(O?"post2":"get");var R="spBeaconPreflight_".concat(a,"_").concat(b);if(d)try{var x=JSON.parse(C.getItem(u))}catch(me){}Array.isArray(x)||(x=[]);c.outQueues.push(x);O&&1<g&&c.bufferFlushers.push(function(){F||L()});return{enqueueRequest:function(a,
b){z=b+N;if(O){a=n(a);if(a.bytes>=h){y("Event of size "+a.bytes+" is too long - the maximum size is "+h);B(z).send(D(A([a.evt])));return}x.push(a)}else x.push(p(a));a=!1;d&&(a=Db(u,JSON.stringify(x.slice(0,m))));F||a&&!(x.length>=g)||L()},executeQueue:L}}function gd(a){var b={};"object"===K(a)&&null!==a&&Object.getOwnPropertyNames(a).forEach(function(c,d,e){"function"===typeof a[c]&&(b[c]=hd(a[c]))});return b}function Ca(a,b,c,d,e){function f(a){return-1<Bb.map(function(a){return a.toLowerCase()}).indexOf(a.toLowerCase())}
function g(){Da=hc(v.domain,w.location.href,Ob());Da[1]!==sa&&(pb=Ob(sa));Fa=Nb(Da[0]);sa=Da[1]}function h(){var a=(new Date).getTime();if(this.href){a="_sp="+(qb+"."+a);var b=this.href.split("#"),c=b[0].split("?"),d=c.shift();if(c=c.join("?")){for(var e=!0,g=c.split("&"),f=0;f<g.length;f++)if("_sp="===g[f].substr(0,4)){e=!1;g[f]=a;c=g.join("&");break}e&&(c=a+"&"+c)}else c=a;b[0]=d+"?"+c;this.href=b.join("#")}}function l(a){for(var b=0;b<v.links.length;b++){var c=v.links[b];!c.spDecorationEnabled&&
a(c)&&(B(c,"click",h,!0),B(c,"mousedown",h,!0),c.spDecorationEnabled=!0)}}function m(a){if(Oa){var b=/#.*/;a=a.replace(b,"")}Qa&&(b=/[{}]/g,a=a.replace(b,""));return a}function r(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function p(a){return Sa+a+"."+hb}function n(a){a=p(a);if("localStorage"==E){a:{try{var b=R.getItem(a+".expires");if(null===b||+b>Date.now()){var c=R.getItem(a);break a}else R.removeItem(a),R.removeItem(a+".expires");c=void 0;break a}catch(ne){}c=void 0}return c}if("cookie"==E||
"cookieAndLocalStorage"==E)return D(a)}function t(){g();hb=yb((Eb||Fa)+(Ga||"/")).slice(0,4)}function L(){Fb=(new Date).getTime()}function A(){var a=J(),b=a[0];b<Gb?Gb=b:b>Hb&&(Hb=b);a=a[1];a<Ib?Ib=a:a>Jb&&(Jb=a);L()}function J(){var a=v.compatMode&&"BackCompat"!==v.compatMode?v.documentElement:v.body;return[a.scrollLeft||w.pageXOffset,a.scrollTop||w.pageYOffset]}function K(){var a=J(),b=a[0];Hb=Gb=b;Jb=Ib=a=a[1]}function C(a){a=Math.round(a);if(!isNaN(a))return a}function F(){var a=p("ses");N(a,
"*",Ka)}function H(a,b,c,d,e,g){var X=p("id");N(X,a+"."+b+"."+c+"."+d+"."+e+"."+g,bb)}function N(a,b,c){if(!ca||Ta)"localStorage"==E?Db(a,b,c):("cookie"==E||"cookieAndLocalStorage"==E)&&D(a,b,c,Ga,Eb,tb,ub)}function T(){var a=p("id"),b=p("ses");fc(a);fc(b);D(a,"",-1,"/",void 0);D(b,"",-1,"/",void 0)}function U(){if(!ca||Ta){var a="none"!=E&&!!n("ses"),b=O();b[1]?qb=b[1]:(qb=ca?"":Q(),b[1]=qb);P=b[6];a||(b[3]++,P=Q(),b[6]=P,b[5]=b[4]);"none"!=E&&(F(),b[4]=Math.round((new Date).getTime()/1E3),b.shift(),
H.apply(null,b))}}function O(){if("none"==E)return[];var a=Math.round((new Date).getTime()/1E3),b=n("id");b?(a=b.split("."),a.unshift("0")):a=["1",qb,a,0,a,""];a[6]||(a[6]=Q());return a}function V(a){return cb?"https://"+a:wb?"http://"+a:("https:"===v.location.protocol?"https":"http")+"://"+a}function u(a){var b=Pb.concat(a||[]);G.webPage&&b.push({schema:"iglu:com.snowplowanalytics.snowplow/web_page/jsonschema/1-0-0",data:{id:x()}});G.performanceTiming&&(a=aa())&&b.push(a);if(w.optimizely){G.optimizelySummary&&
(a=qa(),z(a,function(a){b.push(a)}));G.optimizelyXSummary&&(a=ya(),z(a,function(a){b.push(a)}));if(G.optimizelyExperiments){var c=ia();for(a=0;a<c.length;a++)b.push(c[a])}if(G.optimizelyStates)for(c=ja(),a=0;a<c.length;a++)b.push(c[a]);if(G.optimizelyVariations)for(c=ka(),a=0;a<c.length;a++)b.push(c[a]);G.optimizelyVisitor&&(a=la())&&b.push(a);if(G.optimizelyAudiences)for(c=ma(),a=0;a<c.length;a++)b.push(c[a]);if(G.optimizelyDimensions)for(c=oa(),a=0;a<c.length;a++)b.push(c[a])}G.parrable&&(a=za())&&
b.push(a);G.gdprBasis&&Ea.gdprBasis&&(a=Ea.gdprBasis?{schema:"iglu:com.snowplowanalytics.snowplow/gdpr/jsonschema/1-0-0",data:{basisForProcessing:Ea.gdprBasis,documentId:Ea.gdprDocId||null,documentVersion:Ea.gdprDocVer||null,documentDescription:Ea.gdprDocDesc||null}}:void 0,a&&b.push(a));G.clientHints&&ta&&b.push({schema:"iglu:org.ietf/http_client_hints/jsonschema/1-0-0",data:ta});return b}function W(){lb&&null!=d.pageViewId||(d.pageViewId=Q())}function x(){null==d.pageViewId&&(d.pageViewId=Q());
return d.pageViewId}function aa(){var a="navigationStart redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart secureConnectionStart connectEnd requestStart responseStart responseEnd unloadEventStart unloadEventEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd msFirstPaint chromeFirstPaint requestEnd proxyStart proxyEnd".split(" "),b=w.performance||w.mozPerformance||w.msPerformance||w.webkitPerformance;
if(b){var c={},d;for(d in b.timing)gc(d,a)&&null!==b.timing[d]&&(c[d]=b.timing[d]);delete c.requestEnd;return{schema:"iglu:org.w3/PerformanceTiming/jsonschema/1-0-0",data:c}}}function ba(a,b){if(w.optimizely&&w.optimizely.data){var c=w.optimizely.data[a];"undefined"!==typeof b&&void 0!==c&&(c=c[b])}return c}function Z(a,b){if(w.optimizely&&"function"===typeof w.optimizely.get){var c=w.optimizely.get(a);"undefined"!==typeof b&&void 0!==c&&(c=c[b])}return c}function fa(){var a=ba("state"),b=ba("experiments");
return Aa(a&&b&&a.activeExperiments,function(c){var d=b[c];return{activeExperimentId:c.toString(),variation:a.variationIdsMap[c][0].toString(),conditional:d&&d.conditional,manual:d&&d.manual,name:d&&d.name}})}function ha(){var a=Z("state"),b=a&&a.getActiveExperimentIds(),c=a&&a.getVariationMap(),d=Z("visitor");return Aa(b,function(a){var b=c[a],e=b&&b.name&&b.name.toString()||null;b=b&&b.id;var X=d&&d.visitorId&&d.visitorId.toString()||null;return{experimentId:Ra(a)||null,variationName:e,variation:Ra(b)||
null,visitorId:X}})}function ia(){var a=ba("experiments");if(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d={};d.id=c;var e=a[c];d.code=e.code;d.manual=e.manual;d.conditional=e.conditional;d.name=e.name;d.variationIds=e.variation_ids;b.push({schema:"iglu:com.optimizely/experiment/jsonschema/1-0-0",data:d})}return b}return[]}function ja(){var a=[],b=ba("experiments");if(b)for(var c in b)b.hasOwnProperty(c)&&a.push(c);if(b=ba("state")){c=[];for(var d=b.activeExperiments||[],e=0;e<a.length;e++){var g=
a[e],f={};f.experimentId=g;f.isActive=gc(a[e],d);f.variationIndex=(b.variationMap||{})[g];f.variationName=(b.variationNamesMap||{})[g];var h=b.variationIdsMap||{};h[g]&&1===h[g].length&&(f.variationId=h[g][0]);c.push({schema:"iglu:com.optimizely/state/jsonschema/1-0-0",data:f})}return c}return[]}function ka(){var a=ba("variations");if(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d={};d.id=c;var e=a[c];d.name=e.name;d.code=e.code;b.push({schema:"iglu:com.optimizely/variation/jsonschema/1-0-0",
data:d})}return b}return[]}function la(){var a=ba("visitor");if(a){var b={};b.browser=a.browser;b.browserVersion=a.browserVersion;b.device=a.device;b.deviceType=a.deviceType;b.ip=a.ip;var c=a.platform||{};b.platformId=c.id;b.platformVersion=c.version;c=a.location||{};b.locationCity=c.city;b.locationRegion=c.region;b.locationCountry=c.country;b.mobile=a.mobile;b.mobileId=a.mobileId;b.referrer=a.referrer;b.os=a.os;return{schema:"iglu:com.optimizely/visitor/jsonschema/1-0-0",data:b}}}function ma(){var a=
ba("visitor","audiences");if(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push({schema:"iglu:com.optimizely/visitor_audience/jsonschema/1-0-0",data:{id:c,isMember:a[c]}});return b}return[]}function oa(){var a=ba("visitor","dimensions");if(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push({schema:"iglu:com.optimizely/visitor_dimension/jsonschema/1-0-0",data:{id:c,value:a[c]}});return b}return[]}function qa(){return Aa(fa(),function(a){return{schema:"iglu:com.optimizely.snowplow/optimizely_summary/jsonschema/1-0-0",
data:a}})}function ya(){return Aa(ha(),function(a){return{schema:"iglu:com.optimizely.optimizelyx/summary/jsonschema/1-0-0",data:a}})}function za(){var a=window._hawk;if(a){var b={encryptedId:null,optout:null};b.encryptedId=a.browserid;a=new RegExp("(?:^|;)\\s?"+"_parrable_hawk_optout".replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")+"=(.*?)(?:;|$)","i");a=document.cookie.match(a);b.optout=a&&decodeURIComponent(a[1])?a&&decodeURIComponent(a[1]):"false";return{schema:"iglu:com.parrable/encrypted_payload/jsonschema/1-0-0",
data:b}}}function ua(){!kb&&M.geolocation&&M.geolocation.getCurrentPosition&&(kb=!0,M.geolocation.getCurrentPosition(function(a){var b=a.coords;Pb.push({schema:"iglu:com.snowplowanalytics.snowplow/geolocation_context/jsonschema/1-1-0",data:{latitude:b.latitude,longitude:b.longitude,latitudeLongitudeAccuracy:b.accuracy,altitude:b.altitude,altitudeAccuracy:b.altitudeAccuracy,bearing:b.heading,speed:b.speed,timestamp:Math.round(a.timestamp)}})}))}function Ha(){var a={};z("__utma __utmb __utmc __utmv __utmz _ga".split(" "),
function(b){var c=D(b);c&&(a[b]=c)});return{schema:"iglu:com.google.analytics/cookies/jsonschema/1-0-0",data:a}}function Ia(a,b,c,d,e){g();mb&&W();mb=!0;Ua=v.title;rb=a;a=ec(rb||Ua);q.trackPageView(m(Va||sa),a,m(ea||pb),u((b||[]).concat(c?c():[])),d,e);d=new Date;e=!1;if(S.enabled&&!S.installed){e=S.installed=!0;var X={update:function(){if("undefined"!==typeof window&&"function"===typeof window.addEventListener){var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}}),c=function(){};
window.addEventListener("testPassiveEventSupport",c,b);window.removeEventListener("testPassiveEventSupport",c,b);X.hasSupport=a}}};X.update();a="onwheel"in document.createElement("div")?"wheel":void 0!==document.onmousewheel?"mousewheel":"DOMMouseScroll";Object.prototype.hasOwnProperty.call(X,"hasSupport")?B(v,a,L,{passive:!0}):B(v,a,L);K();a=function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:L;return function(a){return B(v,a,b)}};z("click mouseup mousedown mousemove keypress keydown keyup".split(" "),
a(v));z(["resize","focus","blur"],a(w));a(w,A)("scroll")}if(S.enabled&&(jb||e)){Fb=d.getTime();for(var f in S.configurations)S.configurations.hasOwnProperty(f)&&(d=S.configurations[f],clearInterval(d.activityInterval),Ma(d,(b||[]).concat(c?c():[])))}}function Ma(a,b){var c=function(a,b){g();a({context:b,pageViewId:x(),minXOffset:Gb,minYOffset:Ib,maxXOffset:Hb,maxYOffset:Jb});K()},d=function(){Fb+a.configHeartBeatTimer>(new Date).getTime()&&c(a.callback,b)};a.activityInterval=0!=a.configMinimumVisitLength?
setTimeout(function(){Fb+a.configMinimumVisitLength>(new Date).getTime()&&c(a.callback,b);a.activityInterval=setInterval(d,a.configHeartBeatTimer)},a.configMinimumVisitLength):setInterval(d,a.configHeartBeatTimer)}function wa(a,b,c){if("number"==typeof a&&a==Qb(a)&&"number"==typeof b&&b==Qb(b))return{configMinimumVisitLength:1E3*a,configHeartBeatTimer:1E3*b,activityInterval:null,callback:c};y("Activity tracking not enabled, please provide integer values for minimumVisitLength and heartBeatDelay.");
return{}}function Na(a){var b=a.context,c=a.minXOffset,d=a.minYOffset,e=a.maxXOffset;a=a.maxYOffset;var g=v.title;g!==Ua&&(Ua=g,rb=null);q.trackPagePing(m(Va||sa),ec(rb||Ua),m(ea||pb),C(c),C(e),C(d),C(a),u(b))}function na(a,b){return""!==a?a+b.charAt(0).toUpperCase()+b.slice(1):b}function I(a){var b,c,d=["","webkit","ms","moz"];if(!ab)for(c=0;c<d.length;c++){var e=d[c];if(v[na(e,"hidden")]){"prerender"===v[na(e,"visibilityState")]&&(b=!0);break}else if(!1===v[na(e,"hidden")])break}b?B(v,e+"visibilitychange",
function id(){v.removeEventListener(e+"visibilitychange",id,!1);a()}):a()}e=e||{};e.hasOwnProperty("post")?e.eventMethod=!0===e.post?"post":"get":e.eventMethod=e.eventMethod||"post";e.hasOwnProperty("useStm")||(e.useStm=!0);var xa=function(a){return a.hasOwnProperty("stateStorageStrategy")?a.stateStorageStrategy:Rb||eb?Rb&&eb?"cookieAndLocalStorage":Rb?"cookie":"localStorage":"none"},pa=function(a){return a.hasOwnProperty("anonymousTracking")?!0===a.anonymousTracking.withSessionTracking:!1},Pa=Object.freeze({consent:"consent",
contract:"contract",legalObligation:"legal_obligation",vitalInterests:"vital_interests",publicTask:"public_task",legitimateInterests:"legitimate_interests"}),q=Oc.trackerCore(!0,function(a){var b=Math.round((new Date).getTime()/1E3),c=n("ses"),e=O(),f=e[0],X=e[1],h=e[2],l=e[3],k=e[4],r=e[5];e=e[6];var p=sb?!!D(sb):!1;Ja||p?T():("0"===f?(P=e,c||"none"==E||(l++,r=k,P=Q()),da=l):(new Date).getTime()-Sb>1E3*Ka&&(P=Q(),da++),a.add("vp",Yc()),a.add("ds",Zc()),a.add("vid",Ta?da:ca?null:da),a.add("sid",Ta?
P:ca?null:P),a.add("duid",ca?null:X),a.add("uid",ca?null:Wa),g(),a.add("refr",m(ea||pb)),a.add("url",m(Va||sa)),"none"!=E&&(H(X,h,da,b,r,P),F()),Sb=(new Date).getTime());b=fb;c=new Date;f=sb?!!D(sb):!1;Ja||f||(Tb.enqueueRequest(a.build(),va),d.expireDateTime=c.getTime()+b)}),Ba=!1,k={},ra={},Ca={},v=document,w=window,M=navigator,Da=hc(v.domain,w.location.href,Ob()),Fa=Nb(Da[0]),sa=Da[1],pb=Da[2],ea,Za=e.hasOwnProperty("platform")?e.platform:"web",va,La=e.hasOwnProperty("postPath")?e.postPath:"/com.snowplowanalytics.snowplow/tp2",
db=e.hasOwnProperty("appId")?e.appId:"",Va,Ua=v.title,rb,fb=e.hasOwnProperty("pageUnloadTimer")?e.pageUnloadTimer:500,jb=e.hasOwnProperty("resetActivityTrackingOnPageView")?e.resetActivityTrackingOnPageView:!0,Oa,Qa,Sa=e.hasOwnProperty("cookieName")?e.cookieName:"_sp_",Eb=e.hasOwnProperty("cookieDomain")?e.cookieDomain:null,Ga="/",tb=e.hasOwnProperty("cookieSameSite")?e.cookieSameSite:"None",ub=e.hasOwnProperty("cookieSecure")?e.cookieSecure:!0,$a=M.doNotTrack||M.msDoNotTrack||w.doNotTrack,Ja=e.hasOwnProperty("respectDoNotTrack")?
e.respectDoNotTrack&&("yes"===$a||"1"===$a):!1,sb,ab,bb=e.hasOwnProperty("cookieLifetime")?e.cookieLifetime:63072E3,Ka=e.hasOwnProperty("sessionCookieTimeout")?e.sessionCookieTimeout:1800,vb=v.characterSet||v.charset,cb=e.hasOwnProperty("forceSecureTracker")?!0===e.forceSecureTracker:!1,wb=!cb&&e.hasOwnProperty("forceUnsecureTracker")?!0===e.forceUnsecureTracker:!1,Ta=pa(e),ca=!!e.anonymousTracking,eb=e.hasOwnProperty("useLocalStorage")?(y("argmap.useLocalStorage is deprecated. Use argmap.stateStorageStrategy instead."),
e.useLocalStorage):!0,Rb=e.hasOwnProperty("useCookies")?(y("argmap.useCookies is deprecated. Use argmap.stateStorageStrategy instead."),e.useCookies):!0,E=xa(e),xb=M.userLanguage||M.language,Kb=$c("cookie"==E||"cookieAndLocalStorage"==E,p("testcookie")),gb=a+"_"+b,Fb,Sb=(new Date).getTime(),Gb,Hb,Ib,Jb,yb=jd,hb,qb,P,da=1,Wa,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,Lb=[],Xa=new ad(q,gb,u),Mb=new bd(q,gb,u),ib=new dd(q),Tb=new ic(a,b,d,"localStorage"==E||"cookieAndLocalStorage"==E,e.eventMethod,La,e.bufferSize,
e.maxPostBytes||4E4,e.useStm,e.maxLocalStorageQueueSize||1E3,e.connectionTimeout||5E3),kb=!1,G=e.contexts||{},Pb=[],Ya=[],lb=!1,mb=!1,S={enabled:!1,installed:!1,configurations:{}},ta=null;G.clientHints&&M.userAgentData&&(ta={isMobile:M.userAgentData.mobile,brands:M.userAgentData.brands},G.clientHints.includeHighEntropy&&M.userAgentData.getHighEntropyValues&&M.userAgentData.getHighEntropyValues(["platform","platformVersion","architecture","model","uaFullVersion"]).then(function(a){ta.architecture=
a.architecture;ta.model=a.model;ta.platform=a.platform;ta.uaFullVersion=a.uaFullVersion;ta.platformVersion=a.platformVersion}));var Bb=e.skippedBrowserFeatures||[],Ea={};e.hasOwnProperty("discoverRootDomain")&&e.discoverRootDomain&&(Eb=Uc());G.gaCookies&&Pb.push(Ha());G.geolocation&&ua();q.setBase64Encoding(e.hasOwnProperty("encodeBase64")?e.encodeBase64:!0);q.setTrackerVersion(c);q.setTrackerNamespace(b);q.setAppId(db);q.setPlatform(Za);q.setTimezone(kd.jstz.determine().name());q.addPayloadPair("lang",
xb);q.addPayloadPair("cs",vb);for(var Y in Kb)Object.prototype.hasOwnProperty.call(Kb,Y)&&("res"!==Y&&"cd"!==Y&&"cookie"!==Y||f(Y)?f(Y)||q.addPayloadPair("f_"+Y,Kb[Y]):q.addPayloadPair(Y,Kb[Y]));t();U();e.crossDomainLinker&&l(e.crossDomainLinker);k.getDomainSessionIndex=function(){return da};k.getPageViewId=function(){return x()};k.newSession=function(){var a=Math.round((new Date).getTime()/1E3),b=O(),c=b[1],d=b[2],e=b[3],g=b[4],f=b[5],h=b[6];"0"===b[0]?(P=h,"none"!=E&&(e++,f=g,P=Q()),da=e,F()):(P=
Q(),da++);"none"!=E&&(H(c,d,da,a,f,P),F());Sb=(new Date).getTime()};k.getCookieName=function(a){return p(a)};k.getUserId=function(){return Wa};k.getDomainUserId=function(){return O()[1]};k.getDomainUserInfo=function(){return O()};k.getUserFingerprint=function(){y("User Fingerprinting is no longer supported. This function will be removed in a future release.");return 0};k.setAppId=function(a){y("setAppId is deprecated. Instead use the argmap argument on tracker initialisation: appId");q.setAppId(a)};
k.setReferrerUrl=function(a){ea=a};k.setCustomUrl=function(a){g();var b=sa,c;r(a)?Va=a:"/"===a.slice(0,1)?Va=r(b)+"://"+Cb(b)+a:(b=m(b),0<=(c=b.indexOf("?"))&&(b=b.slice(0,c)),(c=b.lastIndexOf("/"))!==b.length-1&&(b=b.slice(0,c+1)),Va=b+a)};k.setDocumentTitle=function(a){Ua=v.title;rb=a};k.discardHashTag=function(a){Oa=a};k.discardBrace=function(a){Qa=a};k.setCookieNamePrefix=function(a){y("setCookieNamePrefix is deprecated. Instead use the argmap argument on tracker initialisation: cookieName");
Sa=a};k.setCookieDomain=function(a){y("setCookieDomain is deprecated. Instead use the argmap argument on tracker initialisation: cookieDomain");Eb=Nb(a);t()};k.setCookiePath=function(a){Ga=a;t()};k.setVisitorCookieTimeout=function(a){bb=a};k.setSessionCookieTimeout=function(a){y("setSessionCookieTimeout is deprecated. Instead use the argmap argument on tracker initialisation: sessionCookieTimeout");Ka=a};k.setUserFingerprintSeed=function(){y("User Fingerprinting is no longer supported. This function will be removed in a future release.")};
k.enableUserFingerprint=function(){y("User Fingerprinting is no longer supported. This function will be removed in a future release.")};k.respectDoNotTrack=function(a){y("respectDoNotTrack is deprecated. Instead use the argmap argument on tracker initialisation: respectDoNotTrack");var b=M.doNotTrack||M.msDoNotTrack;Ja=a&&("yes"===b||"1"===b)};k.crossDomainLinker=function(a){l(a)};k.enableLinkClickTracking=function(a,b,c,e){d.hasLoaded?(Xa.configureLinkClickTracking(a,b,c,e),Xa.addClickListeners()):
d.registeredOnLoadHandlers.push(function(){Xa.configureLinkClickTracking(a,b,c,e);Xa.addClickListeners()})};k.refreshLinkClickTracking=function(){d.hasLoaded?Xa.addClickListeners():d.registeredOnLoadHandlers.push(function(){Xa.addClickListeners()})};k.enableActivityTracking=function(a,b){S.enabled=!0;S.configurations.pagePing=wa(a,b,Na)};k.enableActivityTrackingCallback=function(a,b,c){S.enabled=!0;S.configurations.callback=wa(a,b,c)};k.updatePageActivity=function(){L()};k.enableFormTracking=function(a,
b){d.hasLoaded?(Mb.configureFormTracking(a),Mb.addFormListeners(b)):d.registeredOnLoadHandlers.push(function(){Mb.configureFormTracking(a);Mb.addFormListeners(b)})};k.killFrame=function(){w.location!==w.top.location&&(w.top.location=w.location)};k.redirectFile=function(a){"file:"===w.location.protocol&&(w.location=a)};k.setOptOutCookie=function(a){sb=a};k.setCountPreRendered=function(a){ab=a};k.setUserId=function(a){Wa=a};k.identifyUser=function(a){k.setUserId(a)};k.setUserIdFromLocation=function(a){g();
Wa=nb(a,sa)};k.setUserIdFromReferrer=function(a){g();Wa=nb(a,pb)};k.setUserIdFromCookie=function(a){Wa=D(a)};k.setCollectorCf=function(a){va=V(a+".cloudfront.net")};k.setCollectorUrl=function(a){va=V(a)};k.setPlatform=function(a){y("setPlatform is deprecated. Instead use the argmap argument on tracker initialisation: platform");q.setPlatform(a)};k.encodeBase64=function(a){y("encodeBase64 is deprecated. Instead use the argmap argument on tracker initialisation: encodeBase64");q.setBase64Encoding(a)};
k.flushBuffer=function(){Tb.executeQueue()};k.enableGeolocationContext=ua;k.trackPageView=function(a,b,c,d,e){I(function(){Ia(a,b,c,d,e)})};k.trackStructEvent=function(a,b,c,d,e,g,f,h){I(function(){q.trackStructEvent(a,b,c,d,e,u(g),f,h)})};k.trackSelfDescribingEvent=function(a,b,c,d){I(function(){q.trackSelfDescribingEvent(a,u(b),c,d)})};k.trackUnstructEvent=function(a,b,c){I(function(){q.trackSelfDescribingEvent(a,u(b),c)})};k.addTrans=function(a,b,c,d,e,g,f,h,l,k,m){Ub=a;Vb=b;Wb=c;Xb=d;Yb=e;Zb=
g;$b=f;ac=h;bc=l;cc=k;dc=m};k.addItem=function(a,b,c,d,e,g,f,h,l){Lb.push({orderId:a,sku:b,name:c,category:d,price:e,quantity:g,currency:f,context:h,tstamp:l})};k.trackTrans=function(){I(function(){var a=dc;q.trackEcommerceTransaction(Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,u(cc),a);for(a=0;a<Lb.length;a++){var b=Lb[a],c=b.tstamp;q.trackEcommerceTransactionItem(b.orderId,b.sku,b.name,b.category,b.price,b.quantity,b.currency,u(b.context),c)}dc=cc=bc=ac=$b=Zb=Yb=Xb=Wb=Vb=Ub=void 0;Lb=[]})};k.trackLinkClick=function(a,
b,c,d,e,g,f){I(function(){q.trackLinkClick(a,b,c,d,e,u(g),f)})};k.trackAdImpression=function(a,b,c,d,e,g,f,h,l,k){I(function(){q.trackAdImpression(a,b,c,d,e,g,f,h,u(l),k)})};k.trackAdClick=function(a,b,c,d,e,g,f,h,l,k,m){I(function(){q.trackAdClick(a,b,c,d,e,g,f,h,l,u(k),m)})};k.trackAdConversion=function(a,b,c,d,e,g,f,h,l,k,m){I(function(){q.trackAdConversion(a,b,c,d,e,g,f,h,l,u(k),m)})};k.trackSocialInteraction=function(a,b,c,d,e){I(function(){q.trackSocialInteraction(a,b,c,u(d),e)})};k.trackAddToCart=
function(a,b,c,d,e,g,f,h){I(function(){q.trackAddToCart(a,b,c,d,e,g,u(f),h)})};k.trackRemoveFromCart=function(a,b,c,d,e,g,f,h){I(function(){q.trackRemoveFromCart(a,b,c,d,e,g,u(f),h)})};k.trackSiteSearch=function(a,b,c,d,e,g){I(function(){q.trackSiteSearch(a,b,c,d,u(e),g)})};k.trackTiming=function(a,b,c,d,e,g){I(function(){q.trackSelfDescribingEvent({schema:"iglu:com.snowplowanalytics.snowplow/timing/jsonschema/1-0-0",data:{category:a,variable:b,timing:c,label:d}},u(e),g)})};k.trackConsentWithdrawn=
function(a,b,c,d,e,g,f){I(function(){q.trackConsentWithdrawn(a,b,c,d,e,u(g),f)})};k.trackConsentGranted=function(a,b,c,d,e,g,f){I(function(){q.trackConsentGranted(a,b,c,d,e,u(g),f)})};k.trackEnhancedEcommerceAction=function(a,b,c){var d=Ya.concat(b||[]);Ya.length=0;I(function(){q.trackSelfDescribingEvent({schema:"iglu:com.google.analytics.enhanced-ecommerce/action/jsonschema/1-0-0",data:{action:a}},u(d),c)})};k.addEnhancedEcommerceActionContext=function(a,b,c,d,e,g,f,h,l,k){Ya.push({schema:"iglu:com.google.analytics.enhanced-ecommerce/actionFieldObject/jsonschema/1-0-0",
data:{id:a,affiliation:b,revenue:ob(c),tax:ob(d),shipping:ob(e),coupon:g,list:f,step:Ra(h),option:l,currency:k}})};k.addEnhancedEcommerceImpressionContext=function(a,b,c,d,e,g,f,h,l){Ya.push({schema:"iglu:com.google.analytics.enhanced-ecommerce/impressionFieldObject/jsonschema/1-0-0",data:{id:a,name:b,list:c,brand:d,category:e,variant:g,position:Ra(f),price:ob(h),currency:l}})};k.addEnhancedEcommerceProductContext=function(a,b,c,d,e,g,f,h,l,k,m){Ya.push({schema:"iglu:com.google.analytics.enhanced-ecommerce/productFieldObject/jsonschema/1-0-0",
data:{id:a,name:b,list:c,brand:d,category:e,variant:g,price:ob(f),quantity:Ra(h),coupon:l,position:Ra(k),currency:m}})};k.addEnhancedEcommercePromoContext=function(a,b,c,d,e){Ya.push({schema:"iglu:com.google.analytics.enhanced-ecommerce/promoFieldObject/jsonschema/1-0-0",data:{id:a,name:b,creative:c,position:d,currency:e}})};k.enableGdprContext=function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:null,d=3<arguments.length&&
void 0!==arguments[3]?arguments[3]:null,e=Pa[a];e?(G.gdprBasis=!0,Ea={gdprBasis:e,gdprDocId:b,gdprDocVer:c,gdprDocDesc:d}):y("enableGdprContext failed. basisForProcessing must be set to one of: consent, legalObligation, vitalInterests publicTask, legitimateInterests")};k.addGlobalContexts=function(a){q.addGlobalContexts(a)};k.removeGlobalContexts=function(a){q.removeGlobalContexts(a)};k.clearGlobalContexts=function(){q.clearGlobalContexts()};k.enableErrorTracking=function(a,b){ib.enableErrorTracking(a,
b,u())};k.trackError=function(a,b,c,d,e,g){g=u(g);ib.trackError(a,b,c,d,e,g)};k.preservePageViewId=function(){lb=!0};k.disableAnonymousTracking=function(c){c?(Object.assign(e,{stateStorageStrategy:c,anonymousTracking:!1}),E=xa(e),Tb=new ic(a,b,d,"localStorage"==E||"cookieAndLocalStorage"==E,e.eventMethod,La,e.bufferSize,e.maxPostBytes||4E4,e.useStm,e.maxLocalStorageQueueSize||1E3,e.connectionTimeout||5E3)):Object.assign(e,{anonymousTracking:!1});ca=!!e.anonymousTracking;Ta=pa(e);U()};k.enableAnonymousTracking=
function(a){Object.assign(e,{anonymousTracking:a||!0});ca=!!e.anonymousTracking;(Ta=pa(e))||W()};k.clearUserData=T;k.setDebug=function(a){Ca=(Ba=(!!a).valueOf())?k:ra};ra=gd(k);return Ca=Ba?k:ra}function lc(a,b){function c(){var a;if(!f.hasLoaded)for(f.hasLoaded=!0,a=0;a<f.registeredOnLoadHandlers.length;a++)f.registeredOnLoadHandlers[a]();return!0}var d=document,e=window,f={outQueues:[],bufferFlushers:[],expireDateTime:null,hasLoaded:!1,registeredOnLoadHandlers:[],pageViewId:null};e.Snowplow={getTrackerCf:function(a){var c=
new Ca(b,"","js-2.16.3",f,{});c.setCollectorCf(a);return c},getTrackerUrl:function(a){var c=new Ca(b,"","js-2.16.3",f,{});c.setCollectorUrl(a);return c},getAsyncTracker:function(){return new Ca(b,"","js-2.16.3",f,{})}};B(e,"beforeunload",function(){z(f.bufferFlushers,function(a){a()});if(f.expireDateTime){do{var a=new Date;if(0===Array.prototype.filter.call(f.outQueues,function(a){return 0<a.length}).length)break}while(a.getTime()<f.expireDateTime)}},!1);(function(){var a;d.addEventListener?B(d,"DOMContentLoaded",
function l(){d.removeEventListener("DOMContentLoaded",l,!1);c()}):d.attachEvent&&(d.attachEvent("onreadystatechange",function l(){"complete"===d.readyState&&(d.detachEvent("onreadystatechange",l),c())}),d.documentElement.doScroll&&e===e.top&&function m(){if(!f.hasLoaded){try{d.documentElement.doScroll("left")}catch(r){setTimeout(m,0);return}c()}}());/WebKit/.test(navigator.userAgent)&&(a=setInterval(function(){if(f.hasLoaded||/loaded|complete/.test(d.readyState))clearInterval(a),c()},10));B(e,"load",
c,!1)})();return new Vc(Ca,"js-2.16.3",f,a,b)}var ld=function(a,b){for(var c=-1,d=null==a?0:a.length;++c<d&&!1!==b(a[c],c,a););return a},md=function(a){return function(b,c,d){var e=-1,f=Object(b);d=d(b);for(var g=d.length;g--;){var h=d[a?g:++e];if(!1===c(f[h],h,f))break}return b}}(),Fa="undefined"!==typeof globalThis?globalThis:"undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:{},mc="object"==K(Fa)&&Fa&&Fa.Object===Object&&Fa,nd="object"==("undefined"===
typeof self?"undefined":K(self))&&self&&self.Object===Object&&self,J=mc||nd||Function("return this")(),T=J.Symbol,nc=Object.prototype,od=nc.hasOwnProperty,pd=nc.toString,ua=T?T.toStringTag:void 0,qd=Object.prototype.toString,oc=T?T.toStringTag:void 0,Z=function(a){if(null==a)a=void 0===a?"[object Undefined]":"[object Null]";else if(oc&&oc in Object(a)){var b=od.call(a,ua),c=a[ua];try{a[ua]=void 0;var d=!0}catch(f){}var e=pd.call(a);d&&(b?a[ua]=c:delete a[ua]);a=e}else a=qd.call(a);return a},W=function(a){return null!=
a&&"object"==K(a)},pc=function(a){return W(a)&&"[object Arguments]"==Z(a)},qc=Object.prototype,rd=qc.hasOwnProperty,sd=qc.propertyIsEnumerable,rc=pc(function(){return arguments}())?pc:function(a){return W(a)&&rd.call(a,"callee")&&!sd.call(a,"callee")},A=Array.isArray,td=function(){return!1},fb=ja(function(a,b){var c=(b=b&&!b.nodeType&&b)&&a&&!a.nodeType&&a;b=c&&c.exports===b?J.Buffer:void 0;a.exports=(b?b.isBuffer:void 0)||td}),ud=/^(?:0|[1-9]\d*)$/,sc=function(a,b){var c=K(a);b=null==b?9007199254740991:
b;return!!b&&("number"==c||"symbol"!=c&&ud.test(a))&&-1<a&&0==a%1&&a<b},Ga=function(a){return"number"==typeof a&&-1<a&&0==a%1&&9007199254740991>=a},n={};n["[object Float32Array]"]=n["[object Float64Array]"]=n["[object Int8Array]"]=n["[object Int16Array]"]=n["[object Int32Array]"]=n["[object Uint8Array]"]=n["[object Uint8ClampedArray]"]=n["[object Uint16Array]"]=n["[object Uint32Array]"]=!0;n["[object Arguments]"]=n["[object Array]"]=n["[object ArrayBuffer]"]=n["[object Boolean]"]=n["[object DataView]"]=
n["[object Date]"]=n["[object Error]"]=n["[object Function]"]=n["[object Map]"]=n["[object Number]"]=n["[object Object]"]=n["[object RegExp]"]=n["[object Set]"]=n["[object String]"]=n["[object WeakMap]"]=!1;var vd=function(a){return W(a)&&Ga(a.length)&&!!n[Z(a)]},wd=function(a){return function(b){return a(b)}},tc=ja(function(a,b){var c=b&&!b.nodeType&&b;c=(b=c&&a&&!a.nodeType&&a)&&b.exports===c&&mc.process;a:{try{var d=b&&b.require&&b.require("util").types;if(d){var e=d;break a}e=c&&c.binding&&c.binding("util");
break a}catch(f){}e=void 0}a.exports=e}),uc=tc&&tc.isTypedArray,xb=uc?wd(uc):vd,xd=Object.prototype.hasOwnProperty,yd=Object.prototype,zd=function(a,b){return function(c){return a(b(c))}}(Object.keys,Object),Ad=Object.prototype.hasOwnProperty,N=function(a){var b=K(a);return null!=a&&("object"==b||"function"==b)},vc=function(a){if(!N(a))return!1;a=Z(a);return"[object Function]"==a||"[object GeneratorFunction]"==a||"[object AsyncFunction]"==a||"[object Proxy]"==a},ea=function(a){return null!=a&&Ga(a.length)&&
!vc(a)},ya=function(a){if(ea(a)){var b=A(a),c=!b&&rc(a),d=!b&&!c&&fb(a),e=!b&&!c&&!d&&xb(a);if(b=b||c||d||e){c=a.length;for(var f=String,g=-1,h=Array(c);++g<c;)h[g]=f(g);c=h}else c=[];f=c.length;for(var l in a)!xd.call(a,l)||b&&("length"==l||d&&("offset"==l||"parent"==l)||e&&("buffer"==l||"byteLength"==l||"byteOffset"==l)||sc(l,f))||c.push(l);a=c}else if(l=a&&a.constructor,a===("function"==typeof l&&l.prototype||yd)){l=[];for(d in Object(a))Ad.call(a,d)&&"constructor"!=d&&l.push(d);a=l}else a=zd(a);
return a},wc=function(a,b){return a&&md(a,b,ya)},tb=function(a,b){return function(c,d){if(null==c)return c;if(!ea(c))return a(c,d);for(var e=c.length,f=b?e:-1,g=Object(c);(b?f--:++f<e)&&!1!==d(g[f],f,g););return c}}(wc),xc=function(a){return a},z=function(a,b){return(A(a)?ld:tb)(a,"function"==typeof b?b:xc)},yc=function(a,b){for(var c=-1,d=null==a?0:a.length,e=0,f=[];++c<d;){var g=a[c];b(g,c,a)&&(f[e++]=g)}return f},Bd=function(a,b){var c=[];tb(a,function(a,e,f){b(a,e,f)&&c.push(a)});return c},zc=
function(a,b){return a===b||a!==a&&b!==b},Za=function(a,b){for(var c=a.length;c--;)if(zc(a[c][0],b))return c;return-1},Cd=Array.prototype.splice;ka.prototype.clear=function(){this.__data__=[];this.size=0};ka.prototype["delete"]=function(a){var b=this.__data__;a=Za(b,a);if(0>a)return!1;a==b.length-1?b.pop():Cd.call(b,a,1);--this.size;return!0};ka.prototype.get=function(a){var b=this.__data__;a=Za(b,a);return 0>a?void 0:b[a][1]};ka.prototype.has=function(a){return-1<Za(this.__data__,a)};ka.prototype.set=
function(a,b){var c=this.__data__,d=Za(c,a);0>d?(++this.size,c.push([a,b])):c[d][1]=b;return this};var wa=ka,ub=J["__core-js_shared__"],Ac=function(){var a=/[^.]+$/.exec(ub&&ub.keys&&ub.keys.IE_PROTO||"");return a?"Symbol(src)_1."+a:""}(),Dd=Function.prototype.toString,fa=function(a){if(null!=a){try{return Dd.call(a)}catch(b){}return a+""}return""},Ed=/^\[object .+?Constructor\]$/,Fd=RegExp("^"+Function.prototype.toString.call(Object.prototype.hasOwnProperty).replace(/[\\^$.*+?()[\]{}|]/g,"\\$&").replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g,
"$1.*?")+"$"),ha=function(a,b){a=null==a?void 0:a[b];return(!N(a)||Ac&&Ac in a?0:(vc(a)?Fd:Ed).test(fa(a)))?a:void 0},Ha=ha(J,"Map"),Ia=ha(Object,"create"),Gd=Object.prototype.hasOwnProperty,Hd=Object.prototype.hasOwnProperty;V.prototype.clear=function(){this.__data__=Ia?Ia(null):{};this.size=0};V.prototype["delete"]=function(a){a=this.has(a)&&delete this.__data__[a];this.size-=a?1:0;return a};V.prototype.get=function(a){var b=this.__data__;return Ia?(a=b[a],"__lodash_hash_undefined__"===a?void 0:
a):Gd.call(b,a)?b[a]:void 0};V.prototype.has=function(a){var b=this.__data__;return Ia?void 0!==b[a]:Hd.call(b,a)};V.prototype.set=function(a,b){var c=this.__data__;this.size+=this.has(a)?0:1;c[a]=Ia&&void 0===b?"__lodash_hash_undefined__":b;return this};var va=function(a,b){a=a.__data__;var c=K(b);return("string"==c||"number"==c||"symbol"==c||"boolean"==c?"__proto__"!==b:null===b)?a["string"==typeof b?"string":"hash"]:a.map};la.prototype.clear=function(){this.size=0;this.__data__={hash:new V,map:new (Ha||
wa),string:new V}};la.prototype["delete"]=function(a){a=va(this,a)["delete"](a);this.size-=a?1:0;return a};la.prototype.get=function(a){return va(this,a).get(a)};la.prototype.has=function(a){return va(this,a).has(a)};la.prototype.set=function(a,b){var c=va(this,a),d=c.size;c.set(a,b);this.size+=c.size==d?0:1;return this};var na=la;ma.prototype.clear=function(){this.__data__=new wa;this.size=0};ma.prototype["delete"]=function(a){var b=this.__data__;a=b["delete"](a);this.size=b.size;return a};ma.prototype.get=
function(a){return this.__data__.get(a)};ma.prototype.has=function(a){return this.__data__.has(a)};ma.prototype.set=function(a,b){var c=this.__data__;if(c instanceof wa){var d=c.__data__;if(!Ha||199>d.length)return d.push([a,b]),this.size=++c.size,this;c=this.__data__=new na(d)}c.set(a,b);this.size=c.size;return this};var xa=ma;Na.prototype.add=Na.prototype.push=function(a){this.__data__.set(a,"__lodash_hash_undefined__");return this};Na.prototype.has=function(a){return this.__data__.has(a)};var Id=
function(a,b){for(var c=-1,d=null==a?0:a.length;++c<d;)if(b(a[c],c,a))return!0;return!1},gb=function(a,b,c,d,e,f){var g=c&1,h=a.length,l=b.length;if(h!=l&&!(g&&l>h))return!1;l=f.get(a);var m=f.get(b);if(l&&m)return l==b&&m==a;l=-1;m=!0;var r=c&2?new Na:void 0;f.set(a,b);for(f.set(b,a);++l<h;){var p=a[l],n=b[l];if(d)var t=g?d(n,p,l,b,a,f):d(p,n,l,a,b,f);if(void 0!==t){if(t)continue;m=!1;break}if(r){if(!Id(b,function(a,b){if(!r.has(b)&&(p===a||e(p,a,c,d,f)))return r.push(b)})){m=!1;break}}else if(p!==
n&&!e(p,n,c,d,f)){m=!1;break}}f["delete"](a);f["delete"](b);return m},Bc=J.Uint8Array,Jd=function(a){var b=-1,c=Array(a.size);a.forEach(function(a,e){c[++b]=[e,a]});return c},Kd=function(a){var b=-1,c=Array(a.size);a.forEach(function(a){c[++b]=a});return c},Cc=T?T.prototype:void 0,$a=Cc?Cc.valueOf:void 0,Pc=function(a,b,c,d,e,f,g){switch(c){case "[object DataView]":if(a.byteLength!=b.byteLength||a.byteOffset!=b.byteOffset)break;a=a.buffer;b=b.buffer;case "[object ArrayBuffer]":if(a.byteLength!=b.byteLength||
!f(new Bc(a),new Bc(b)))break;return!0;case "[object Boolean]":case "[object Date]":case "[object Number]":return zc(+a,+b);case "[object Error]":return a.name==b.name&&a.message==b.message;case "[object RegExp]":case "[object String]":return a==b+"";case "[object Map]":var h=Jd;case "[object Set]":h||(h=Kd);if(a.size!=b.size&&!(d&1))break;if(c=g.get(a))return c==b;d|=2;g.set(a,b);b=gb(h(a),h(b),d,e,f,g);g["delete"](a);return b;case "[object Symbol]":if($a)return $a.call(a)==$a.call(b)}return!1},
hb=function(a,b,c){b=b(a);if(!A(a)){a=c(a);c=-1;for(var d=a.length,e=b.length;++c<d;)b[e+c]=a[c]}return b},Ld=function(){return[]},Md=Object.prototype.propertyIsEnumerable,Dc=Object.getOwnPropertySymbols,ib=Dc?function(a){if(null==a)return[];a=Object(a);return yc(Dc(a),function(b){return Md.call(a,b)})}:Ld,Qc=Object.prototype.hasOwnProperty,Ja=ha(J,"DataView"),ab=ha(J,"Promise"),bb=ha(J,"Set"),Ka=ha(J,"WeakMap"),Nd=fa(Ja),Od=fa(Ha),Pd=fa(ab),Qd=fa(bb),Rd=fa(Ka),ia=Z;if(Ja&&"[object DataView]"!=ia(new Ja(new ArrayBuffer(1)))||
Ha&&"[object Map]"!=ia(new Ha)||ab&&"[object Promise]"!=ia(ab.resolve())||bb&&"[object Set]"!=ia(new bb)||Ka&&"[object WeakMap]"!=ia(new Ka))ia=function(a){var b=Z(a);if(a=(a="[object Object]"==b?a.constructor:void 0)?fa(a):"")switch(a){case Nd:return"[object DataView]";case Od:return"[object Map]";case Pd:return"[object Promise]";case Qd:return"[object Set]";case Rd:return"[object WeakMap]"}return b};var eb=ia,yb=Object.prototype.hasOwnProperty,Sd=function(a,b,c,d){var e=c.length,f=e,g=!d;if(null==
a)return!f;for(a=Object(a);e--;){var h=c[e];if(g&&h[2]?h[1]!==a[h[0]]:!(h[0]in a))return!1}for(;++e<f;){h=c[e];var l=h[0],m=a[l],r=h[1];if(g&&h[2]){if(void 0===m&&!(l in a))return!1}else{h=new xa;if(d)var n=d(m,r,l,a,b,h);if(void 0===n?!oa(r,m,3,d,h):!n)return!1}}return!0},Td=function(a){for(var b=ya(a),c=b.length;c--;){var d=b[c],e=a[d];b[c]=[d,e,e===e&&!N(e)]}return b},Ec=function(a,b){return function(c){return null==c?!1:c[a]===b&&(void 0!==b||a in Object(c))}},Ud=function(a){var b=Td(a);return 1==
b.length&&b[0][2]?Ec(b[0][0],b[0][1]):function(c){return c===a||Sd(c,a,b)}},pa=function(a){return"symbol"==K(a)||W(a)&&"[object Symbol]"==Z(a)},Vd=/\.|\[(?:[^[\]]*|(["'])(?:(?!\1)[^\\]|\\.)*?\1)\]/,Wd=/^\w*$/,vb=function(a,b){if(A(a))return!1;var c=K(a);return"number"==c||"symbol"==c||"boolean"==c||null==a||pa(a)?!0:Wd.test(a)||!Vd.test(a)||null!=b&&a in Object(b)};jb.Cache=na;var Xd=/[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\\]|\\.)*?)\2)\]|(?=(?:\.|\[\])(?:\.|\[\]|$))/g,Yd=/\\(\\)?/g,Zd=
function(a){a=jb(a,function(a){500===b.size&&b.clear();return a});var b=a.cache;return a}(function(a){var b=[];46===a.charCodeAt(0)&&b.push("");a.replace(Xd,function(a,d,e,f){b.push(e?f.replace(Yd,"$1"):d||a)});return b}),lb=function(a,b){for(var c=-1,d=null==a?0:a.length,e=Array(d);++c<d;)e[c]=b(a[c],c,a);return e},Rc=1/0,Fc=T?T.prototype:void 0,mb=Fc?Fc.toString:void 0,Gc=function(a,b){return A(a)?a:vb(a,b)?[a]:Zd(null==a?"":kb(a))},$d=1/0,La=function(a){if("string"==typeof a||pa(a))return a;var b=
a+"";return"0"==b&&1/a==-$d?"-0":b},Hc=function(a,b){b=Gc(b,a);for(var c=0,d=b.length;null!=a&&c<d;)a=a[La(b[c++])];return c&&c==d?a:void 0},ae=function(a,b){return vb(a)&&b===b&&!N(b)?Ec(La(a),b):function(c){var d=null==c?void 0:Hc(c,a);d=void 0===d?void 0:d;if(void 0===d&&d===b){if(d=null!=c){d=a;d=Gc(d,c);for(var e=-1,f=d.length,g=!1;++e<f;){var h=La(d[e]);if(!(g=null!=c&&null!=c&&h in Object(c)))break;c=c[h]}g||++e!=f?d=g:(f=null==c?0:c.length,d=!!f&&Ga(f)&&sc(h,f)&&(A(c)||rc(c)))}h=d}else h=
oa(b,d,3);return h}},be=function(a){return function(b){return null==b?void 0:b[a]}},ce=function(a){return function(b){return Hc(b,a)}},Ma=function(a){return"function"==typeof a?a:null==a?xc:"object"==K(a)?A(a)?ae(a[0],a[1]):Ud(a):vb(a)?be(La(a)):ce(a)},Sc=function(a,b){return(A(a)?yc:Bd)(a,Ma(b))},Bb=function(a){return"string"==typeof a||!A(a)&&W(a)&&"[object String]"==Z(a)},de=function(a,b){var c=-1,d=ea(a)?Array(a.length):[];tb(a,function(a,f,g){d[++c]=b(a,f,g)});return d},Aa=function(a,b){return(A(a)?
lb:de)(a,Ma(b))},aa=window,za=document,R=window.localStorage,kc=window.sessionStorage,Ic=0/0,ee=/^\s+|\s+$/g,fe=/^[-+]0x[0-9a-f]+$/i,ge=/^0b[01]+$/i,he=/^0o[0-7]+$/i,ie=parseInt,je=function(a){if("number"==typeof a)return a;if(pa(a))return Ic;N(a)&&(a="function"==typeof a.valueOf?a.valueOf():a,a=N(a)?a+"":a);if("string"!=typeof a)return 0===a?a:+a;a=a.replace(ee,"");var b=ge.test(a);return b||he.test(a)?ie(a.slice(2),b?2:8):fe.test(a)?Ic:+a},Jc=1/0,Qb=function(a){a?(a=je(a),a=a===Jc||a===-Jc?1.7976931348623157E308*
(0>a?-1:1):a===a?a:0):a=0===a?a:0;var b=a%1;return a===a?b?a-b:a:0},kd=ja(function(a,b){(function(a){var c=function(){var a=function(a){a=-a.getTimezoneOffset();return null!==a?a:0},b=function(a,b,c){var d=new Date;void 0!==a&&d.setFullYear(a);d.setMonth(b);d.setDate(c);return d};return{determine:function(){var d=a(b(void 0,0,2)),e=a(b(void 0,5,2)),f=d-e;return new c.TimeZone(c.olson.timezones[0>f?d+",1":0<f?e+",1,s":d+",0"])},date_is_dst:function(c){var d=7<c.getMonth(),e=d?a(b(c.getFullYear(),5,
2)):a(b(c.getFullYear(),0,2));c=a(c);c=e-c;return 0>e||d?0!==c:0>c},dst_start_for:function(a){var b=new Date(2010,6,15,1,0,0,0);return{"America/Denver":new Date(2011,2,13,3,0,0,0),"America/Mazatlan":new Date(2011,3,3,3,0,0,0),"America/Chicago":new Date(2011,2,13,3,0,0,0),"America/Mexico_City":new Date(2011,3,3,3,0,0,0),"America/Asuncion":new Date(2012,9,7,3,0,0,0),"America/Santiago":new Date(2012,9,3,3,0,0,0),"America/Campo_Grande":new Date(2012,9,21,5,0,0,0),"America/Montevideo":new Date(2011,9,
2,3,0,0,0),"America/Sao_Paulo":new Date(2011,9,16,5,0,0,0),"America/Los_Angeles":new Date(2011,2,13,8,0,0,0),"America/Santa_Isabel":new Date(2011,3,5,8,0,0,0),"America/Havana":new Date(2012,2,10,2,0,0,0),"America/New_York":new Date(2012,2,10,7,0,0,0),"Europe/Helsinki":new Date(2013,2,31,5,0,0,0),"Pacific/Auckland":new Date(2011,8,26,7,0,0,0),"America/Halifax":new Date(2011,2,13,6,0,0,0),"America/Goose_Bay":new Date(2011,2,13,2,1,0,0),"America/Miquelon":new Date(2011,2,13,5,0,0,0),"America/Godthab":new Date(2011,
2,27,1,0,0,0),"Europe/Moscow":b,"Asia/Amman":new Date(2013,2,29,1,0,0,0),"Asia/Beirut":new Date(2013,2,31,2,0,0,0),"Asia/Damascus":new Date(2013,3,6,2,0,0,0),"Asia/Jerusalem":new Date(2013,2,29,5,0,0,0),"Asia/Yekaterinburg":b,"Asia/Omsk":b,"Asia/Krasnoyarsk":b,"Asia/Irkutsk":b,"Asia/Yakutsk":b,"Asia/Vladivostok":b,"Asia/Baku":new Date(2013,2,31,4,0,0),"Asia/Yerevan":new Date(2013,2,31,3,0,0),"Asia/Kamchatka":b,"Asia/Gaza":new Date(2010,2,27,4,0,0),"Africa/Cairo":new Date(2010,4,1,3,0,0),"Europe/Minsk":b,
"Pacific/Apia":new Date(2010,10,1,1,0,0,0),"Pacific/Fiji":new Date(2010,11,1,0,0,0),"Australia/Perth":new Date(2008,10,1,1,0,0,0)}[a]}}}();c.TimeZone=function(a){var b={"America/Denver":["America/Denver","America/Mazatlan"],"America/Chicago":["America/Chicago","America/Mexico_City"],"America/Santiago":["America/Santiago","America/Asuncion","America/Campo_Grande"],"America/Montevideo":["America/Montevideo","America/Sao_Paulo"],"Asia/Beirut":["Asia/Amman","Asia/Jerusalem","Asia/Beirut","Europe/Helsinki",
"Asia/Damascus"],"Pacific/Auckland":["Pacific/Auckland","Pacific/Fiji"],"America/Los_Angeles":["America/Los_Angeles","America/Santa_Isabel"],"America/New_York":["America/Havana","America/New_York"],"America/Halifax":["America/Goose_Bay","America/Halifax"],"America/Godthab":["America/Miquelon","America/Godthab"],"Asia/Dubai":["Europe/Moscow"],"Asia/Dhaka":["Asia/Yekaterinburg"],"Asia/Jakarta":["Asia/Omsk"],"Asia/Shanghai":["Asia/Krasnoyarsk","Australia/Perth"],"Asia/Tokyo":["Asia/Irkutsk"],"Australia/Brisbane":["Asia/Yakutsk"],
"Pacific/Noumea":["Asia/Vladivostok"],"Pacific/Tarawa":["Asia/Kamchatka","Pacific/Fiji"],"Pacific/Tongatapu":["Pacific/Apia"],"Asia/Baghdad":["Europe/Minsk"],"Asia/Baku":["Asia/Yerevan","Asia/Baku"],"Africa/Johannesburg":["Asia/Gaza","Africa/Cairo"]},d=a;a=function(){for(var a=b[d],e=a.length,f=0,g;f<e;f+=1)if(g=a[f],c.date_is_dst(c.dst_start_for(g))){d=g;break}};"undefined"!==typeof b[d]&&a();return{name:function(){return d}}};c.olson={};c.olson.timezones={"-720,0":"Pacific/Majuro","-660,0":"Pacific/Pago_Pago",
"-600,1":"America/Adak","-600,0":"Pacific/Honolulu","-570,0":"Pacific/Marquesas","-540,0":"Pacific/Gambier","-540,1":"America/Anchorage","-480,1":"America/Los_Angeles","-480,0":"Pacific/Pitcairn","-420,0":"America/Phoenix","-420,1":"America/Denver","-360,0":"America/Guatemala","-360,1":"America/Chicago","-360,1,s":"Pacific/Easter","-300,0":"America/Bogota","-300,1":"America/New_York","-270,0":"America/Caracas","-240,1":"America/Halifax","-240,0":"America/Santo_Domingo","-240,1,s":"America/Santiago",
"-210,1":"America/St_Johns","-180,1":"America/Godthab","-180,0":"America/Argentina/Buenos_Aires","-180,1,s":"America/Montevideo","-120,0":"America/Noronha","-120,1":"America/Noronha","-60,1":"Atlantic/Azores","-60,0":"Atlantic/Cape_Verde","0,0":"UTC","0,1":"Europe/London","60,1":"Europe/Berlin","60,0":"Africa/Lagos","60,1,s":"Africa/Windhoek","120,1":"Asia/Beirut","120,0":"Africa/Johannesburg","180,0":"Asia/Baghdad","180,1":"Europe/Moscow","210,1":"Asia/Tehran","240,0":"Asia/Dubai","240,1":"Asia/Baku",
"270,0":"Asia/Kabul","300,1":"Asia/Yekaterinburg","300,0":"Asia/Karachi","330,0":"Asia/Kolkata","345,0":"Asia/Kathmandu","360,0":"Asia/Dhaka","360,1":"Asia/Omsk","390,0":"Asia/Rangoon","420,1":"Asia/Krasnoyarsk","420,0":"Asia/Jakarta","480,0":"Asia/Shanghai","480,1":"Asia/Irkutsk","525,0":"Australia/Eucla","525,1,s":"Australia/Eucla","540,1":"Asia/Yakutsk","540,0":"Asia/Tokyo","570,0":"Australia/Darwin","570,1,s":"Australia/Adelaide","600,0":"Australia/Brisbane","600,1":"Asia/Vladivostok","600,1,s":"Australia/Sydney",
"630,1,s":"Australia/Lord_Howe","660,1":"Asia/Kamchatka","660,0":"Pacific/Noumea","690,0":"Pacific/Norfolk","720,1,s":"Pacific/Auckland","720,0":"Pacific/Tarawa","765,1,s":"Pacific/Chatham","780,0":"Pacific/Tongatapu","780,1,s":"Pacific/Apia","840,0":"Pacific/Kiritimati"};b.jstz=c})()}),qa=window,H=navigator,Sa=screen,ra=document,cb=ja(function(a){(function(){var b={rotl:function(a,b){return a<<b|a>>>32-b},rotr:function(a,b){return a<<32-b|a>>>b},endian:function(a){if(a.constructor==Number)return b.rotl(a,
8)&16711935|b.rotl(a,24)&4278255360;for(var c=0;c<a.length;c++)a[c]=b.endian(a[c]);return a},randomBytes:function(a){for(var b=[];0<a;a--)b.push(Math.floor(256*Math.random()));return b},bytesToWords:function(a){for(var b=[],c=0,f=0;c<a.length;c++,f+=8)b[f>>>5]|=a[c]<<24-f%32;return b},wordsToBytes:function(a){for(var b=[],c=0;c<32*a.length;c+=8)b.push(a[c>>>5]>>>24-c%32&255);return b},bytesToHex:function(a){for(var b=[],c=0;c<a.length;c++)b.push((a[c]>>>4).toString(16)),b.push((a[c]&15).toString(16));
return b.join("")},hexToBytes:function(a){for(var b=[],c=0;c<a.length;c+=2)b.push(parseInt(a.substr(c,2),16));return b},bytesToBase64:function(a){for(var b=[],c=0;c<a.length;c+=3)for(var f=a[c]<<16|a[c+1]<<8|a[c+2],g=0;4>g;g++)8*c+6*g<=8*a.length?b.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(f>>>6*(3-g)&63)):b.push("=");return b.join("")},base64ToBytes:function(a){a=a.replace(/[^A-Z0-9+\/]/ig,"");for(var b=[],c=0,f=0;c<a.length;f=++c%4)0!=f&&b.push(("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a.charAt(c-
1))&Math.pow(2,-2*f+8)-1)<<2*f|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a.charAt(c))>>>6-2*f);return b}};a.exports=b})()}),wb={utf8:{stringToBytes:function(a){return wb.bin.stringToBytes(unescape(encodeURIComponent(a)))},bytesToString:function(a){return decodeURIComponent(escape(wb.bin.bytesToString(a)))}},bin:{stringToBytes:function(a){for(var b=[],c=0;c<a.length;c++)b.push(a.charCodeAt(c)&255);return b},bytesToString:function(a){for(var b=[],c=0;c<a.length;c++)b.push(String.fromCharCode(a[c]));
return b.join("")}}},Kc=wb,jd=ja(function(a){(function(){var b=Kc.utf8,c=Kc.bin,d=function(a){a.constructor==String&&(a=b.stringToBytes(a));var c=cb.bytesToWords(a),d=8*a.length;a=[];var e=1732584193,f=-271733879,n=-1732584194,p=271733878,t=-1009589776;c[d>>5]|=128<<24-d%32;c[(d+64>>>9<<4)+15]=d;for(d=0;d<c.length;d+=16){for(var y=e,z=f,A=n,B=p,D=t,C=0;80>C;C++){if(16>C)a[C]=c[d+C];else{var F=a[C-3]^a[C-8]^a[C-14]^a[C-16];a[C]=F<<1|F>>>31}F=(e<<5|e>>>27)+t+(a[C]>>>0)+(20>C?(f&n|~f&p)+1518500249:40>
C?(f^n^p)+1859775393:60>C?(f&n|f&p|n&p)-1894007588:(f^n^p)-899497514);t=p;p=n;n=f<<30|f>>>2;f=e;e=F}e+=y;f+=z;n+=A;p+=B;t+=D}return[e,f,n,p,t]},e=function(a,b){a=cb.wordsToBytes(d(a));return b&&b.asBytes?a:b&&b.asString?c.bytesToString(a):cb.bytesToHex(a)};e._blocksize=16;e._digestsize=20;a.exports=e})()}),ke=Math.max,cd=function(a){return function(b,c,d){var e=Object(b);if(!ea(b)){var f=Ma(c);b=ya(b);c=function(a){return f(e[a],a,e)}}c=a(b,c,d);return-1<c?e[f?b[c]:c]:void 0}}(function(a,b,c){var d=
null==a?0:a.length;if(!d)return-1;c=null==c?0:Qb(c);0>c&&(c=ke(d+c,0));a:{b=Ma(b);d=a.length;for(c+=-1;++c<d;)if(b(a[c],c,a)){a=c;break a}a=-1}return a}),ed=window,Lc=function(){try{var a=ha(Object,"defineProperty");a({},"",{});return a}catch(b){}}(),fd=function(a,b){var c={};b=Ma(b);wc(a,function(a,e,f){a=b(a,e,f);"__proto__"==e&&Lc?Lc(c,e,{configurable:!0,enumerable:!0,value:a,writable:!0}):c[e]=a});return c},hd=function(a){return function(){try{return a.apply(this,arguments)}catch(b){}}},le=ja(function(a){var b=
"undefined"!=typeof crypto&&crypto.getRandomValues&&crypto.getRandomValues.bind(crypto)||"undefined"!=typeof msCrypto&&"function"==typeof window.msCrypto.getRandomValues&&msCrypto.getRandomValues.bind(msCrypto);if(b){var c=new Uint8Array(16);a.exports=function(){b(c);return c}}else{var d=Array(16);a.exports=function(){for(var a=0,b;16>a;a++)0===(a&3)&&(b=4294967296*Math.random()),d[a]=b>>>((a&3)<<3)&255;return d}}}),t=[],db=0;for(;256>db;++db)t[db]=(db+256).toString(16).substr(1);var Q=function(a,
b,c){c=b&&c||0;"string"==typeof a&&(b="binary"===a?Array(16):null,a=null);a=a||{};a=a.random||(a.rng||le)();a[6]=a[6]&15|64;a[8]=a[8]&63|128;if(b)for(var d=0;16>d;++d)b[c+d]=a[d];b||(b=0,b=[t[a[b++]],t[a[b++]],t[a[b++]],t[a[b++]],"-",t[a[b++]],t[a[b++]],"-",t[a[b++]],t[a[b++]],"-",t[a[b++]],t[a[b++]],"-",t[a[b++]],t[a[b++]],t[a[b++]],t[a[b++]],t[a[b++]],t[a[b++]]].join(""));return b},U=window;if(U.GlobalSnowplowNamespace&&0<U.GlobalSnowplowNamespace.length){var Mc=U.GlobalSnowplowNamespace.shift();
var Nc=U[Mc];Nc.q=new lc(Nc.q,Mc)}else U._snaq=U._snaq||[],U._snaq=new lc(U._snaq,"_snaq")})(snowplowTrackerCore)
